### ISSUE TITLE
Regarding the UI for adding loklak option 

### ISSUE THREAD

**Issue by sopu** [loklak/wp-recent-tweets-plugin#2]
The current UI for twitter authentication is located in the appearance section rather than settings section. 
So I believe loklak option should be added here only?
![selection_007](https://cloud.githubusercontent.com/assets/6399612/15865529/c6b2a77c-2cf8-11e6-8ab0-288839458eae.png)

**Comment by sopu** [comment]
Currently I have added the following UI. Its open for discussion though. 
![selection_008](https://cloud.githubusercontent.com/assets/6399612/15869339/a2de2e32-2d09-11e6-9a41-d49fbbfeb5a4.png)

**Comment by mariobehling** [comment]
Please move the option to the very top and add links:
User anonymous [loklak.org](http://loklak.org) API instead of twitter. [Find out more](http://loklak.org)

**Comment by sopu** [comment]
d8c38db fixes it! 
![selection_009](https://cloud.githubusercontent.com/assets/6399612/15898555/6bb8e3b8-2db6-11e6-828f-eced55bfb4a3.png)

**Comment by mariobehling** [comment]
Please move it one line higher - above SumoMe Plugin - and correct the text: "Find out more"

**Comment by mariobehling** [comment]
I think in order not to confuse people in this plugin best is to:
* [ ] when the tick for loklak is made, deactivate Consumer Key, Consumer Secret, Access Token, Access Token Secret

**Comment by sopu** [comment]
@mariobehling I initially tried to make it "Find out more" but it goes to next line. 
![selection_015](https://cloud.githubusercontent.com/assets/6399612/15926994/9e1ec79a-2e5c-11e6-8628-98b5594343c8.png)

Regarding deactivation! Should it be done just here or in settings page as well? eg. in [wp-twitter-plugin](https://github.com/loklak/wp-twitter-widget)

**Comment by mariobehling** [comment]
> Regarding deactivation! Should it be done just here or in settings page as well?

We need to look at every plugin individually. In this use case specifically, it is confusing if the lines are not greyed out, cause you tick loklak and then might think you still have to fill out the keys.

* [ ] Please also make loklak.org into a link as the example shows.

**Comment by sopu** [comment]
Opened a dedicated issue! #6
