### ISSUE TITLE
Add loklak info to settings page

### ISSUE THREAD

**Issue by mariobehling** [loklak/wp-recent-tweets-plugin#5]
The current widget in the settings area shows instructions to get started with the plugin. Please update the text to inform about loklak as follows [Link to Seetings Area in Sample Site](https://somethingtothink.com/wp-admin/admin.php?page=recent-tweets).
![screenshot from 2016-06-08 18 19 44](https://cloud.githubusercontent.com/assets/1583873/15902122/ab92adda-2da6-11e6-803b-c59e87054813.png)

Make text as follows:
---
You can either simply tick loklak.org in the widget settings to use the anonymous [loklak.org](http://loklak.org) service (no registration required) to get tweets showing up in your widget or follow the steps below to connect to twitter.

1. Go to your Widgets menu, add the Recent Tweets widget to a widget area.
2. Visit https://apps.twitter.com/, sign in with your account, click on Create New App and create your own keys if you haven't already.
3. Fill all your widget settings.
4. Enjoy your new Twitter feed! :)

**Comment by sopu** [comment]
8c9bee7 fixes it! Closing.
![selection_016](https://cloud.githubusercontent.com/assets/6399612/15927227/dc954570-2e5d-11e6-90f2-4b9a466025f4.png)
